version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      # Forzar rebuild sin cache
      args:
        - BUILDKIT_INLINE_CACHE=0
    container_name: aly-gestion
    restart: unless-stopped

    ports:
      - "3001:3001"  # Backend API
      - "9002:9002"  # Frontend

    environment:
      NODE_ENV: production
      PORT: 3001
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:9002}
      JWT_SECRET: ${JWT_SECRET:-622fa71351110f18a8e8226dd1a75c40c9f29a4f6ea6939b1040e4ca0ff4305c}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-7d}
      DATABASE_URL: file:/app/backend/data/prod.db
      FRONTEND_PORT: 9002
      BACKEND_URL: http://localhost:3001
      NEXT_PUBLIC_API_URL: /api

    volumes:
      - aly-gestion-db:/app/backend/data
      - aly-gestion-logs:/app/logs

    networks:
      - aly-network

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9002"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# ================================
# Volúmenes persistentes
# ================================
volumes:
  aly-gestion-db:
    driver: local
    name: aly-gestion-db

  aly-gestion-logs:
    driver: local
    name: aly-gestion-logs

# ================================
# Red
# ================================
networks:
  aly-network:
    driver: bridge
    name: aly-network
